### ISSUE TITLE
import { AppModule } from './app/app.module'; not found

### ISSUE THREAD

**Issue by Leonmcnamara** [chrisnurse/qiksar#1]
Hi Chris

I am intrueged by Qiksar. It seems like it will make my journey a LOT smoother.

Being fairly new to Vue/Quasar, I have been experimenting, the latest being GQL onto my Django GQL backend.

I have been through your YouTube tutorial and needed to try for myself.

When running the build-services.sh  I get the above error.
Can you please assist?

Many Thanks
Leon

**Comment by chrisnurse** [comment]
Hey Leon, great to hear from you. Many thanks for joining the community. I did see this error myself a couple of days ago and it may be there is a file missing from a previous commit. Bear with me, I'll try look into this over the weekend.

**Comment by chrisnurse** [comment]
Hi Leon,

Just had a quick luck. I had made a silly error with the .gitignore which caused the api/app folder to be excluded.
I've fixed the ignore file and pushed a fix.
Hopefully that will get you back on your way :)

Cheers
Chris

**Comment by Leonmcnamara** [comment]
Good morning Chris

Thank you for your prompt response.

This open source community is such a breath of fresh air...amazing ...

Will definitely try it when I surface in a few hours...

**Comment by Leonmcnamara** [comment]
Hi Chris

I have been following the readme. But still getting errors(see attached).
I am building a(nother) travel app and was going to look at a graph DB at
some point. For now the groups and members are in postgres.

What you are building definitely touches a lot of sweet spots for me and
would really like to pursue this route and assist where I can.

Many Thanks
Leon

ps, I am in Cape Town
Enjoy the rugby tomorrow

**Comment by chrisnurse** [comment]
Hi Leon was there an attachment?
